name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: '0 0 * * 0' # weekly
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib

    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@main
        with:
          GH_USERNAME: your-username
